fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /admin

_homepage:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: easyadmin, permanent: true }

