combos :
  type: rest
  resource:     "AppBundle:CombosRest"
  name_prefix:  api_

categorias :
  type: rest
  resource:     "AppBundle:CategoriasRest"
  name_prefix:  api_

pedidos :
  type: rest
  resource:     "AppBundle:PedidosRest"
  name_prefix:  api_
