#easy admin
easy_admin:
    site_name: %site_name%
    entities:
        Empresa:
            class: AppBundle\Entity\Empresa
        Cliente:
            class: AppBundle\Entity\Cliente
        Combo:
            class: AppBundle\Entity\Combo
        UnidadMedida:
            class: AppBundle\Entity\UnidadMedida
        PedidoCabecera:
            class: AppBundle\Entity\PedidoCabecera
        DescuentoEmpresa:
            class: AppBundle\Entity\DescuentoEmpresa
        DescuentoProducto:
            class: AppBundle\Entity\DescuentoProducto
        Pais:
            class: Matudelatower\UbicacionBundle\Entity\Pais
        Provincia:
            class: Matudelatower\UbicacionBundle\Entity\Provincia
        Departamento:
            class: Matudelatower\UbicacionBundle\Entity\Departamento
        Localidad:
            class: Matudelatower\UbicacionBundle\Entity\Localidad
    design:
        form_theme: ['::image_layout.html.twig']
        menu:
            - 'Empresa'
            - 'Producto'
            - 'Cliente'
            - { entity: 'Categoria', label: 'Categoria' }
            - 'Combo'
            - { entity: 'UnidadMedida', label: 'Unidades de Medida' }
            - label: 'Pedidos'
              children:
                - { entity: 'PedidoCabecera', label: 'Pedidos comunes' }
                - { label: 'Pedidos Sergio', route: 'pedidos' }
            - label: 'Descuentos'
              children:
                - { entity: 'DescuentoEmpresa', label: 'Descuento Empresa' }
                - { entity: 'DescuentoProducto', label: 'Descuento Producto' }
            - label: 'Ubicación'
              children:
                  - 'Pais'
                  - 'Provincia'
                  - 'Departamento'
                  - 'Localidad'
            - 'Usuario'
            - { label: 'Cerrar Sesion', route: 'fos_user_security_logout', icon: 'sign-out' }
