easy_admin:
    entities:
        Producto:
            class: AppBundle\Entity\Producto
            list:
                fields:
                    - { property: 'nombre' }
                    - { property: 'descripcion' }
                    - { property: 'controlaStock' }
                    - { property: 'cantidad' }
                    - { property: 'precioDeVenta' }
                    - { property: 'precioDeCosto' }
                    - { property: 'image', type: 'image', template:'field_image', base_path: '%app.path.product_images%' }
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'descripcion' }
                    - { property: 'controlaStock' }
                    - { property: 'cantidad' }
                    - { property: 'precioDeVenta' }
                    - { property: 'precioDeCosto' }
                    - { property: 'empresa' }
                    - { property: 'categoria' }
                    - { property: 'imageFile', template:'field_image',type: 'vich_image' }